{
	"openapi": "3.0.0",
	"components": {
		"examples": {},
		"headers": {},
		"parameters": {},
		"requestBodies": {},
		"responses": {},
		"schemas": {
			"ITsoaSuccessResponse__tags-string-Array__": {
				"properties": {
					"resultType": {
						"type": "string"
					},
					"error": {
						"type": "number",
						"enum": [
							null
						],
						"nullable": true
					},
					"success": {
						"properties": {
							"tags": {
								"items": {
									"type": "string"
								},
								"type": "array"
							}
						},
						"required": [
							"tags"
						],
						"type": "object"
					}
				},
				"required": [
					"resultType",
					"error",
					"success"
				],
				"type": "object",
				"additionalProperties": false
			},
			"FieldErrors": {
				"properties": {},
				"type": "object",
				"additionalProperties": {
					"properties": {
						"value": {},
						"message": {
							"type": "string"
						}
					},
					"required": [
						"message"
					],
					"type": "object"
				}
			},
			"ErrorDetails": {
				"anyOf": [
					{
						"properties": {
							"folderName": {
								"type": "string"
							},
							"userId": {
								"type": "string"
							},
							"folderId": {
								"type": "string"
							}
						},
						"type": "object"
					},
					{
						"properties": {
							"imageUrl": {
								"type": "string"
							},
							"imageId": {
								"type": "string"
							}
						},
						"type": "object"
					},
					{
						"properties": {
							"userId": {
								"type": "string"
							},
							"challengeId": {
								"type": "string"
							}
						},
						"type": "object"
					},
					{
						"properties": {
							"longitude": {
								"type": "number",
								"format": "double"
							},
							"latitude": {
								"type": "number",
								"format": "double"
							}
						},
						"type": "object"
					},
					{
						"properties": {
							"reason": {
								"type": "string"
							}
						},
						"type": "object"
					},
					{
						"properties": {
							"searchKeyword": {
								"type": "string"
							}
						},
						"type": "object"
					},
					{
						"$ref": "#/components/schemas/FieldErrors"
					},
					{
						"properties": {
							"extension": {
								"type": "string"
							}
						},
						"type": "object"
					},
					{
						"properties": {
							"imageId": {
								"items": {
									"type": "string"
								},
								"type": "array"
							},
							"folderId": {
								"type": "string"
							}
						},
						"type": "object"
					}
				],
				"nullable": true
			},
			"ITsoaErrorResponse": {
				"properties": {
					"resultType": {
						"type": "string"
					},
					"error": {
						"properties": {
							"data": {
								"$ref": "#/components/schemas/ErrorDetails"
							},
							"reason": {
								"type": "string"
							},
							"errorCode": {
								"type": "string"
							}
						},
						"required": [
							"data",
							"reason",
							"errorCode"
						],
						"type": "object"
					},
					"success": {
						"type": "number",
						"enum": [
							null
						],
						"nullable": true
					}
				},
				"required": [
					"resultType",
					"error",
					"success"
				],
				"type": "object",
				"additionalProperties": false
			},
			"ITsoaSuccessResponse__id-string--mediaId-string_-Array_": {
				"properties": {
					"resultType": {
						"type": "string"
					},
					"error": {
						"type": "number",
						"enum": [
							null
						],
						"nullable": true
					},
					"success": {
						"items": {
							"properties": {
								"mediaId": {
									"type": "string"
								},
								"id": {
									"type": "string"
								}
							},
							"required": [
								"mediaId",
								"id"
							],
							"type": "object"
						},
						"type": "array"
					}
				},
				"required": [
					"resultType",
					"error",
					"success"
				],
				"type": "object",
				"additionalProperties": false
			},
			"MemoFolderImageResponseDto": {
				"properties": {
					"folderId": {
						"type": "string"
					},
					"folderName": {
						"type": "string"
					},
					"imageId": {
						"type": "string"
					},
					"imageUrl": {
						"type": "string"
					}
				},
				"required": [
					"folderId",
					"folderName",
					"imageId",
					"imageUrl"
				],
				"type": "object",
				"additionalProperties": false
			},
			"ITsoaSuccessResponse_MemoFolderImageResponseDto_": {
				"properties": {
					"resultType": {
						"type": "string"
					},
					"error": {
						"type": "number",
						"enum": [
							null
						],
						"nullable": true
					},
					"success": {
						"$ref": "#/components/schemas/MemoFolderImageResponseDto"
					}
				},
				"required": [
					"resultType",
					"error",
					"success"
				],
				"type": "object",
				"additionalProperties": false
			},
			"MemoTextImageListResponseDto": {
				"properties": {
					"folderId": {
						"type": "string"
					},
					"folderName": {
						"type": "string"
					},
					"imageText": {
						"type": "string"
					},
					"images": {
						"items": {
							"properties": {
								"imageUrl": {
									"type": "string"
								},
								"imageId": {
									"type": "string"
								}
							},
							"required": [
								"imageUrl",
								"imageId"
							],
							"type": "object"
						},
						"type": "array",
						"nullable": true
					}
				},
				"required": [
					"folderId",
					"folderName",
					"imageText",
					"images"
				],
				"type": "object",
				"additionalProperties": false
			},
			"ITsoaSuccessResponse_MemoTextImageListResponseDto_": {
				"properties": {
					"resultType": {
						"type": "string"
					},
					"error": {
						"type": "number",
						"enum": [
							null
						],
						"nullable": true
					},
					"success": {
						"$ref": "#/components/schemas/MemoTextImageListResponseDto"
					}
				},
				"required": [
					"resultType",
					"error",
					"success"
				],
				"type": "object",
				"additionalProperties": false
			},
			"BodyToMemoImagesToMove": {
				"properties": {
					"targetFolderId": {
						"type": "string"
					},
					"imageId": {
						"items": {
							"type": "string"
						},
						"type": "array"
					}
				},
				"required": [
					"targetFolderId",
					"imageId"
				],
				"type": "object",
				"additionalProperties": false
			},
			"ResponseMessage": {
				"properties": {
					"message": {
						"type": "string"
					}
				},
				"required": [
					"message"
				],
				"type": "object",
				"additionalProperties": false
			},
			"ITsoaSuccessResponse_ResponseMessage_": {
				"properties": {
					"resultType": {
						"type": "string"
					},
					"error": {
						"type": "number",
						"enum": [
							null
						],
						"nullable": true
					},
					"success": {
						"$ref": "#/components/schemas/ResponseMessage"
					}
				},
				"required": [
					"resultType",
					"error",
					"success"
				],
				"type": "object",
				"additionalProperties": false
			},
			"MemoFolderResponseDto": {
				"properties": {
					"id": {
						"type": "string"
					},
					"folderName": {
						"type": "string"
					}
				},
				"required": [
					"id",
					"folderName"
				],
				"type": "object",
				"additionalProperties": false
			},
			"ITsoaSuccessResponse_MemoFolderResponseDto_": {
				"properties": {
					"resultType": {
						"type": "string"
					},
					"error": {
						"type": "number",
						"enum": [
							null
						],
						"nullable": true
					},
					"success": {
						"$ref": "#/components/schemas/MemoFolderResponseDto"
					}
				},
				"required": [
					"resultType",
					"error",
					"success"
				],
				"type": "object",
				"additionalProperties": false
			},
			"BodyToMemoFolder": {
				"properties": {
					"folderName": {
						"type": "string"
					}
				},
				"required": [
					"folderName"
				],
				"type": "object",
				"additionalProperties": false
			},
			"MemoFolderListResponseDto": {
				"properties": {
					"folderId": {
						"type": "string"
					},
					"folderName": {
						"type": "string"
					},
					"imageText": {
						"type": "string"
					},
					"imageCount": {
						"type": "number",
						"format": "double"
					},
					"firstImageId": {
						"type": "string",
						"nullable": true
					},
					"firstImageUrl": {
						"type": "string",
						"nullable": true
					},
					"createdAt": {
						"type": "string",
						"format": "date-time"
					}
				},
				"required": [
					"folderId",
					"folderName",
					"imageText",
					"imageCount",
					"firstImageId",
					"firstImageUrl",
					"createdAt"
				],
				"type": "object",
				"additionalProperties": false
			},
			"ITsoaSuccessResponse__data-MemoFolderListResponseDto-Array__": {
				"properties": {
					"resultType": {
						"type": "string"
					},
					"error": {
						"type": "number",
						"enum": [
							null
						],
						"nullable": true
					},
					"success": {
						"properties": {
							"data": {
								"items": {
									"$ref": "#/components/schemas/MemoFolderListResponseDto"
								},
								"type": "array"
							}
						},
						"required": [
							"data"
						],
						"type": "object"
					}
				},
				"required": [
					"resultType",
					"error",
					"success"
				],
				"type": "object",
				"additionalProperties": false
			},
			"BodyToMemoImagesToDelete": {
				"properties": {
					"imageId": {
						"items": {
							"type": "string"
						},
						"type": "array"
					}
				},
				"required": [
					"imageId"
				],
				"type": "object",
				"additionalProperties": false
			},
			"BodyToMemoTextToUpdate": {
				"properties": {
					"memoText": {
						"type": "string"
					}
				},
				"required": [
					"memoText"
				],
				"type": "object",
				"additionalProperties": false
			}
		},
		"securitySchemes": {
			"sessionAuth": {
				"type": "apiKey",
				"in": "cookie",
				"name": "connect.sid"
			}
		}
	},
	"info": {
		"title": "sweepic-server",
		"version": "1.0.0",
		"description": "Sweepic 프로젝트",
		"license": {
			"name": "ISC"
		},
		"contact": {}
	},
	"paths": {
		"/tags/date": {
			"get": {
				"operationId": "GetTagListWithDate",
				"responses": {
					"200": {
						"description": "OK",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaSuccessResponse__tags-string-Array__"
								}
							}
						}
					},
					"400": {
						"description": "Bad Request",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaErrorResponse"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "VAL-001",
												"reason": "Validation Error",
												"data": {
													"year": {
														"message": "invalid float",
														"value": "a"
													}
												}
											},
											"success": null
										}
									}
								}
							}
						}
					},
					"404": {
						"description": "Not Found",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaErrorResponse"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "TAG-001",
												"reason": "태그가 없습니다.",
												"data": null
											},
											"success": null
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "Internal Server Error",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaErrorResponse"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "SER-001",
												"reason": "내부 서버 오류입니다.",
												"data": null
											},
											"success": null
										}
									},
									"Example 2": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "DB-001",
												"reason": "DB 에러 입니다.",
												"data": null
											},
											"success": null
										}
									}
								}
							}
						}
					}
				},
				"description": "사용자가 날짜를 입력하면 해당 날짜에 찍은 사진들의 태그를 검색합니다.\r\n\r\ndate를 입력하지 않으면 해당 월에 찍은 사진들의 태그를 검색합니다.",
				"summary": "날짜기반 태그 검색 API",
				"tags": [
					"Tag"
				],
				"security": [],
				"parameters": [
					{
						"description": "년",
						"in": "query",
						"name": "year",
						"required": true,
						"schema": {
							"format": "double",
							"type": "number"
						}
					},
					{
						"description": "월",
						"in": "query",
						"name": "month",
						"required": true,
						"schema": {
							"format": "double",
							"type": "number"
						}
					},
					{
						"description": "일",
						"in": "query",
						"name": "date",
						"required": false,
						"schema": {
							"format": "double",
							"type": "number"
						}
					}
				]
			}
		},
		"/images": {
			"get": {
				"operationId": "GetImageListFromTag",
				"responses": {
					"200": {
						"description": "OK",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaSuccessResponse__id-string--mediaId-string_-Array_"
								}
							}
						}
					},
					"400": {
						"description": "Bad Request",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaErrorResponse"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "VAL-001",
												"reason": "Validation Error",
												"data": {
													"tag": {
														"message": "\"tag\" is required"
													}
												}
											},
											"success": null
										}
									}
								}
							}
						}
					},
					"404": {
						"description": "Not Found",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaErrorResponse"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "PHO-404",
												"reason": "<인하대학교교> 태그에 해당하는 사진이 존재하지 않습니다.",
												"data": null
											},
											"success": null
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "Internal Server Error",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaErrorResponse"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "SER-001",
												"reason": "내부 서버 오류입니다.",
												"data": null
											},
											"success": null
										}
									},
									"Example 2": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "DB-001",
												"reason": "DB 에러 입니다.",
												"data": null
											},
											"success": null
										}
									}
								}
							}
						}
					}
				},
				"description": "사용자가 tag를 입력하면 해당 태그에 속하는 이미지들을 가져옵니다.",
				"summary": "태그기반 이미지 검색",
				"tags": [
					"Image"
				],
				"security": [],
				"parameters": [
					{
						"description": "태그 내용",
						"in": "query",
						"name": "tag",
						"required": true,
						"schema": {
							"type": "string"
						}
					}
				]
			}
		},
		"/memo/image-format/folders/{folderId}": {
			"post": {
				"operationId": "HandlerMemoImageAdd",
				"responses": {
					"200": {
						"description": "사진 저장 성공 응답",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaSuccessResponse_MemoFolderImageResponseDto_"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "SUCCESS",
											"error": null,
											"success": {
												"folderId": "1",
												"folderName": "string",
												"imageId": "1",
												"imageUrl": "string"
											}
										}
									}
								}
							}
						}
					},
					"400": {
						"description": "유효하지 않은 확장자 에러",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaErrorResponse"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "MEM-400",
												"reason": "메모 사진 추가 중 오류가 발생했습니다.",
												"data": {
													"folderId": "1",
													"imageUrl": "string"
												}
											},
											"success": null
										}
									},
									"Example 2": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "PHO-400",
												"reason": "사진 데이터가 유효하지 않습니다.",
												"data": {
													"extension": "string"
												}
											},
											"success": null
										}
									}
								}
							}
						}
					},
					"404": {
						"description": "존재하지 않은 데이터 조회 에러",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaErrorResponse"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "FOL-404",
												"reason": "해당 폴더를 찾을 수 없습니다.",
												"data": {
													"folderId": "1"
												}
											},
											"success": null
										}
									},
									"Example 2": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "PHO-404",
												"reason": "해당 사진 데이터가 없습니다.",
												"data": {
													"imageId": "1"
												}
											},
											"success": null
										}
									}
								}
							}
						}
					}
				},
				"description": "특정 폴더에 사진을 저장하는 API입니다.",
				"summary": "사진 저장 API",
				"tags": [
					"memo-image-controller"
				],
				"security": [],
				"parameters": [
					{
						"description": "폴더 ID",
						"in": "path",
						"name": "folderId",
						"required": true,
						"schema": {
							"type": "string"
						}
					}
				],
				"requestBody": {
					"required": true,
					"content": {
						"multipart/form-data": {
							"schema": {
								"type": "object",
								"properties": {
									"image": {
										"type": "string",
										"format": "binary"
									}
								},
								"required": [
									"image"
								]
							}
						}
					}
				}
			}
		},
		"/memo/folders/{folderId}/images": {
			"patch": {
				"operationId": "HandlerMemoImageMove",
				"responses": {
					"200": {
						"description": "사진 이동 성공 응답",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaSuccessResponse_MemoTextImageListResponseDto_"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "SUCCESS",
											"error": null,
											"success": {
												"folderId": "1",
												"folderName": "string",
												"imageText": "string",
												"images": [
													{
														"imageId": "1",
														"imageUrl": "string"
													}
												]
											}
										}
									}
								}
							}
						}
					},
					"400": {
						"description": "유효하지 않은 데이터 조회 에러",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaErrorResponse"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "MEM-400",
												"reason": "메모 사진 이동 중 오류가 발생했습니다.",
												"data": {
													"folderId": "1",
													"imageId": [
														"1"
													]
												}
											},
											"success": null
										}
									}
								}
							}
						}
					},
					"404": {
						"description": "존재하지 않은 데이터 조회 에러",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaErrorResponse"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "FOL-404",
												"reason": "해당 폴더를 찾을 수 없습니다.",
												"data": {
													"folderId": "1"
												}
											},
											"success": null
										}
									},
									"Example 2": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "PHO-404",
												"reason": "해당 사진 데이터가 없습니다.",
												"data": {
													"imageId": "1"
												}
											},
											"success": null
										}
									}
								}
							}
						}
					}
				},
				"description": "특정 폴더의 사진을 이동하는 API입니다.",
				"summary": "사진 이동 API",
				"tags": [
					"memo-image-controller"
				],
				"security": [],
				"parameters": [
					{
						"description": "현재 폴더 ID",
						"in": "path",
						"name": "folderId",
						"required": true,
						"schema": {
							"type": "string"
						}
					}
				],
				"requestBody": {
					"description": "이동할 폴더 ID, 이동할 사진 배열",
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/BodyToMemoImagesToMove",
								"description": "이동할 폴더 ID, 이동할 사진 배열"
							}
						}
					}
				}
			}
		},
		"/memo/folders/{folderId}": {
			"delete": {
				"operationId": "HandlerMemoFolderDelete",
				"responses": {
					"200": {
						"description": "폴더 삭제 성공 응답",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaSuccessResponse_ResponseMessage_"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "SUCCESS",
											"error": null,
											"success": {
												"message": "string"
											}
										}
									}
								}
							}
						}
					},
					"404": {
						"description": "존재하지 않은 데이터 조회 에러",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaErrorResponse"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "FOL-404",
												"reason": "해당 폴더를 찾을 수 없습니다.",
												"data": {
													"folderId": "1"
												}
											},
											"success": null
										}
									}
								}
							}
						}
					}
				},
				"description": "특정 폴더의 사진을 삭제하는 API입니다.",
				"summary": "폴더 삭제 API",
				"tags": [
					"memo-folder-controller"
				],
				"security": [],
				"parameters": [
					{
						"description": "폴더 ID",
						"in": "path",
						"name": "folderId",
						"required": true,
						"schema": {
							"type": "string"
						}
					}
				]
			},
			"get": {
				"operationId": "HandlerMemoTextImageList",
				"responses": {
					"200": {
						"description": "메모 조회 성공 응답",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaSuccessResponse_MemoTextImageListResponseDto_"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "SUCCESS",
											"error": null,
											"success": {
												"folderId": "1",
												"folderName": "string",
												"imageText": "string",
												"images": [
													{
														"imageId": "1",
														"imageUrl": "string"
													}
												]
											}
										}
									}
								}
							}
						}
					},
					"404": {
						"description": "존재하지 않은 데이터 조회 에러",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaErrorResponse"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "FOL-404",
												"reason": "해당 폴더를 찾을 수 없습니다.",
												"data": {
													"folderId": "1"
												}
											},
											"success": null
										}
									}
								}
							}
						}
					}
				},
				"description": "특정 폴더의 모든 메모(텍스트 및 사진)을 조회하는 API입니다.",
				"summary": "특정 폴더의 메모 조회 API",
				"tags": [
					"memo-folder-controller"
				],
				"security": [],
				"parameters": [
					{
						"description": "폴더 ID",
						"in": "path",
						"name": "folderId",
						"required": true,
						"schema": {
							"type": "string"
						}
					}
				]
			},
			"patch": {
				"operationId": "HandlerMemoFolderUpdate",
				"responses": {
					"200": {
						"description": "폴더 이름 수정 성공 응답",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaSuccessResponse_MemoTextImageListResponseDto_"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "SUCCESS",
											"error": null,
											"success": {
												"folderId": "1",
												"folderName": "string",
												"imageText": "string",
												"images": [
													{
														"imageId": "1",
														"imageUrl": "string"
													}
												]
											}
										}
									}
								}
							}
						}
					},
					"400": {
						"description": "유효하지 않은 데이터 에러",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaErrorResponse"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "FAIL",
											"success": null,
											"error": {
												"errorCode": "FOL-400",
												"reason": "폴더 업데이트 중 오류가 발생했습니다.",
												"data": {
													"folderId": "1"
												}
											}
										}
									},
									"Example 2": {
										"value": {
											"resultType": "FAIL",
											"success": null,
											"error": {
												"errorCode": "FOL-400",
												"reason": "변경 전의 폴더 이름과 같습니다.",
												"data": {
													"folderName": "string"
												}
											}
										}
									}
								}
							}
						}
					},
					"404": {
						"description": "존재하지 않은 데이터 조회 에러",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaErrorResponse"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "FOL-404",
												"reason": "해당 폴더를 찾을 수 없습니다.",
												"data": {
													"folderId": "1"
												}
											},
											"success": null
										}
									}
								}
							}
						}
					},
					"409": {
						"description": "중복 데이터 에러",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaErrorResponse"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "FAIL",
											"success": null,
											"error": {
												"errorCode": "FOL-409",
												"reason": "이미 존재하는 폴더 이름입니다.",
												"data": {
													"folderName": "string"
												}
											}
										}
									}
								}
							}
						}
					}
				},
				"description": "특정 폴더의 이름을 수정하는 API입니다.",
				"summary": "메모 폴더 이름 수정 API",
				"tags": [
					"memo-folder-controller"
				],
				"security": [],
				"parameters": [
					{
						"description": "폴더 ID",
						"in": "path",
						"name": "folderId",
						"required": true,
						"schema": {
							"type": "string"
						}
					}
				],
				"requestBody": {
					"description": "폴더 이름 수정 내용",
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/BodyToMemoFolder",
								"description": "폴더 이름 수정 내용"
							}
						}
					}
				}
			}
		},
		"/memo/image-format/folders": {
			"post": {
				"operationId": "HandlerMemoFolderImageAdd",
				"responses": {
					"200": {
						"description": "폴더 생성 및 사진 저장 성공 응답",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaSuccessResponse_MemoFolderImageResponseDto_"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "SUCCESS",
											"error": null,
											"success": {
												"folderId": "1",
												"folderName": "string",
												"imageId": "1",
												"imageUrl": "string"
											}
										}
									}
								}
							}
						}
					},
					"400": {
						"description": "유효하지 않은 데이터 에러",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaErrorResponse"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "FAIL",
											"success": null,
											"error": {
												"errorCode": "FOL-400",
												"reason": "폴더 생성 중 오류가 발생했습니다.",
												"data": {
													"userId": "1",
													"folderName": "string"
												}
											}
										}
									},
									"Example 2": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "PHO-400",
												"reason": "사진 데이터가 유효하지 않습니다.",
												"data": {
													"reason": "저장할 사진이 없습니다."
												}
											},
											"success": null
										}
									},
									"Example 3": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "MEM-400",
												"reason": "메모 사진 추가 중 오류가 발생했습니다.",
												"data": {
													"folderId": "1",
													"imageUrl": "string"
												}
											},
											"success": null
										}
									},
									"Example 4": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "PHO-400",
												"reason": "사진 데이터가 유효하지 않습니다.",
												"data": {
													"extension": "string"
												}
											},
											"success": null
										}
									}
								}
							}
						}
					},
					"409": {
						"description": "중복 데이터 에러",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaErrorResponse"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "FAIL",
											"success": null,
											"error": {
												"errorCode": "FOL-409",
												"reason": "이미 존재하는 폴더 이름입니다.",
												"data": {
													"folderName": "string"
												}
											}
										}
									}
								}
							}
						}
					}
				},
				"description": "폴더 생성과 동시에 파일을 저장하는 API입니다.",
				"summary": "폴더 생성 및 사진 저장 API",
				"tags": [
					"memo-folder-controller"
				],
				"security": [],
				"parameters": [],
				"requestBody": {
					"required": true,
					"content": {
						"multipart/form-data": {
							"schema": {
								"type": "object",
								"properties": {
									"folderName": {
										"type": "string",
										"description": "생성할 폴더 이름"
									},
									"image": {
										"type": "string",
										"format": "binary",
										"description": "파일 업로드"
									}
								},
								"required": [
									"folderName",
									"image"
								]
							}
						}
					}
				}
			}
		},
		"/memo/folders": {
			"post": {
				"operationId": "HandlerMemoFolderAdd",
				"responses": {
					"200": {
						"description": "폴더 생성 성공 응답",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaSuccessResponse_MemoFolderResponseDto_"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "SUCCESS",
											"error": null,
											"success": {
												"id": "1",
												"folderName": "string"
											}
										}
									}
								}
							}
						}
					},
					"400": {
						"description": "유효하지 않은 데이터 에러",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaErrorResponse"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "FAIL",
											"success": null,
											"error": {
												"errorCode": "FOL-400",
												"reason": "폴더 생성 중 오류가 발생했습니다.",
												"data": {
													"userId": "1",
													"folderName": "string"
												}
											}
										}
									}
								}
							}
						}
					},
					"409": {
						"description": "중복 데이터 에러",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaErrorResponse"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "FAIL",
											"success": null,
											"error": {
												"errorCode": "FOL-409",
												"reason": "이미 존재하는 폴더 이름입니다.",
												"data": {
													"folderName": "string"
												}
											}
										}
									}
								}
							}
						}
					}
				},
				"description": "폴더를 생성하는 API입니다.",
				"summary": "폴더 생성 API",
				"tags": [
					"memo-folder-controller"
				],
				"security": [],
				"parameters": [],
				"requestBody": {
					"description": "생성할 폴더 이름",
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/BodyToMemoFolder",
								"description": "생성할 폴더 이름"
							}
						}
					}
				}
			}
		},
		"/memo/list": {
			"get": {
				"operationId": "HandlerMemoFolderList",
				"responses": {
					"200": {
						"description": "메모 조회 성공 응답",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaSuccessResponse__data-MemoFolderListResponseDto-Array__"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "SUCCESS",
											"error": null,
											"success": {
												"data": [
													{
														"folderId": "1",
														"folderName": "string",
														"imageCount": 0,
														"imageText": "string",
														"firstImageId": "1",
														"firstImageUrl": "string",
														"createdAt": "2025-01-17T03:50:25.923Z"
													}
												]
											}
										}
									}
								}
							}
						}
					}
				},
				"description": "모든 메모를 조회하는 API입니다.",
				"summary": "모든 메모 조회 API",
				"tags": [
					"memo-folder-controller"
				],
				"security": [],
				"parameters": []
			}
		},
		"/memo/search": {
			"get": {
				"operationId": "HandlerMemoSearch",
				"responses": {
					"200": {
						"description": "메모 검색 성공 응답",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaSuccessResponse__data-MemoFolderListResponseDto-Array__"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "SUCCESS",
											"error": null,
											"success": {
												"data": [
													{
														"folderId": "1",
														"folderName": "string",
														"imageCount": 0,
														"imageText": "string",
														"firstImageId": "1",
														"firstImageUrl": "string",
														"createdAt": "2025-01-17T03:50:25.923Z"
													}
												]
											}
										}
									}
								}
							}
						}
					},
					"400": {
						"description": "유효하지 않은 검색 키워드 에러",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaErrorResponse"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "FAIL",
											"success": null,
											"error": {
												"errorCode": "SRH-400",
												"reason": "입력 데이터가 유효하지 않습니다.",
												"data": {
													"reason": "검색어를 1자 이상 입력하세요."
												}
											}
										}
									}
								}
							}
						}
					}
				},
				"description": "메모를 검색 및 조회하는 API입니다.",
				"summary": "메모 검색 API",
				"tags": [
					"memo-folder-controller"
				],
				"security": [],
				"parameters": [
					{
						"description": "검색 키워드",
						"in": "query",
						"name": "keyword",
						"required": true,
						"schema": {
							"type": "string"
						}
					}
				]
			}
		},
		"/memo/folders/{folderId}/images/delete": {
			"post": {
				"operationId": "HandlerMemoImageDelete",
				"responses": {
					"200": {
						"description": "사진 삭제 성공 응답",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaSuccessResponse_MemoTextImageListResponseDto_"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "SUCCESS",
											"error": null,
											"success": {
												"folderId": "1",
												"folderName": "string",
												"imageText": "string",
												"images": [
													{
														"imageId": "1",
														"imageUrl": "string"
													}
												]
											}
										}
									}
								}
							}
						}
					},
					"404": {
						"description": "존재하지 않은 데이터 조회 에러",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaErrorResponse"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "FOL-404",
												"reason": "해당 폴더를 찾을 수 없습니다.",
												"data": {
													"folderId": "1"
												}
											},
											"success": null
										}
									},
									"Example 2": {
										"value": {
											"resultType": "FAIL",
											"error": {
												"errorCode": "PHO-404",
												"reason": "해당 사진 데이터가 없습니다.",
												"data": {
													"imageId": "1"
												}
											},
											"success": null
										}
									}
								}
							}
						}
					}
				},
				"description": "특정 폴더의 사진을 삭제하는 API입니다.",
				"summary": "사진 삭제 API",
				"tags": [
					"memo-image-controller"
				],
				"security": [],
				"parameters": [
					{
						"description": "폴더 ID",
						"in": "path",
						"name": "folderId",
						"required": true,
						"schema": {
							"type": "string"
						}
					}
				],
				"requestBody": {
					"description": "이동할 사진 ID 배열",
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/BodyToMemoImagesToDelete",
								"description": "이동할 사진 ID 배열"
							}
						}
					}
				}
			}
		},
		"/memo/folders/{folderId}/text": {
			"patch": {
				"operationId": "HandlerMemoTextUpdate",
				"responses": {
					"200": {
						"description": "메모 텍스트 수정 성공 응답",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaSuccessResponse_MemoTextImageListResponseDto_"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "SUCCESS",
											"error": null,
											"success": {
												"folderId": "1",
												"folderName": "string",
												"imageText": "string",
												"images": [
													{
														"imageId": "1",
														"imageUrl": "string"
													}
												]
											}
										}
									}
								}
							}
						}
					},
					"404": {
						"description": "존재하지 않은 데이터 조회 에러",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ITsoaErrorResponse"
								},
								"examples": {
									"Example 1": {
										"value": {
											"resultType": "FAIL",
											"success": null,
											"error": {
												"errorCode": "FOL-404",
												"reason": "해당 폴더를 찾을 수 없습니다.",
												"data": {
													"folderId": "1"
												}
											}
										}
									}
								}
							}
						}
					}
				},
				"description": "특정 폴더의 메모 텍스트를 수정하는 API입니다.",
				"summary": "특정 폴더의 메모 텍스트 수정 API",
				"tags": [
					"memo-folder-controller"
				],
				"security": [],
				"parameters": [
					{
						"description": "폴더 ID",
						"in": "path",
						"name": "folderId",
						"required": true,
						"schema": {
							"type": "string"
						}
					}
				],
				"requestBody": {
					"description": "메모 텍스트 수정 내용",
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/BodyToMemoTextToUpdate",
								"description": "메모 텍스트 수정 내용"
							}
						}
					}
				}
			}
		}
	},
	"servers": [
		{
			"url": "http://localhost:3000",
			"description": "Sweepic local server"
		},
		{
			"url": "http://3.37.137.212:3000",
			"description": "Sweepic server"
		}
	]
}